import type { Metadata } from "next";
// import { Inter, Plus_Jakarta_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Sidebar from "@/components/SideBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "mana components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
        <div className="grid grid-cols-12 h-full">
          {/* Sidebar */}
          <div className="col-span-3 border-r border-border">
            <Sidebar />
          </div>

          {/* Scrollable Content */}
          <div className="col-span-9 overflow-y-auto p-8 bg-background">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
